language: node_js
node_js:
- '4'
- '5'
- '6'
before_script:
- npm install
script:
- npm run test
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@niteoholdings.com
  api_key:
    secure: ZI0def4avjMvDwvVKWNqVbihsjU5riCJVoMVfjpLPS4hLlDA429TNi4P5qY4iNvZB6zmy2Q1lic1LzTcVlBecMhb+aVuuY7EKtU30rJJgHAWqmlVzUU9wxJJe2JrwvYF6M7LrYpgGTkRZm8Wwe3pPk/EdQA2AM4ljiNoBEHx7Guofr79F1o/6P2Qsmap7aP09D7iS5hyLxOcyucsyDac85FfGxXgbgxxNuxSGoOr+SYhFFtRXC8HB/d7W2afBhCFY+SUfmVdWqguPRR85smZzokYgTDhjsTB5EjEzE3K5fQjVadilruuSbGZBOT6vABAeyof4P3lbOihgbOHkL9blKGuRIvVAmOSXpfEpd+MttYVVe/PLE4z5eFfPfnO9SSADZRTt25PM1IbGnJj7SkKnUkQTvQBuJNDgMQBzT2aZNorCtXD+UkWgI45tKkx/H+uwUh81a3dhyfHIEIOI6uK9wOqD/wqJ6pSxqN9N3WoCcZCY8NInFTJCrChWijN1x0TA4zJ99od6eokZf9RamDIw4rFZMEsjzJo9jIJtlfSzRcq5WE77kreJU+j/kCCPEPjJm9iHHyvb2aLgDmS6EhXxzXOYQp0Jl0gFHFyc2G6khuYat7mY6W19Vw6xVrRcny+XqUfWVU0IRW1VX92JDBPLrSbv3yvunLEb3hI8epTWsI=
  on:
    tags: true
    all_branches: master
    repo: VeriShip/tommy
    node: '4'
